CREATE TABLE PlayerAsset (
  AssetId INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  PlayerId INT NOT NULL,
  FlagImgPath VARCHAR(255) NOT NULL,
  PlayerImgPath VARCHAR(255) NOT NULL,
  CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (PlayerId) REFERENCES Player(PlayerId)
);