INSERT INTO PlayerAsset (PlayerId, FlagImgPath, PlayerImgPath)
VALUES (
    '1',
    '/client/assets/flags/rs.svg',
    '/client/assets/players/djokovic.png'
  ),
  (
    '2',
    '/client/assets/flags/es.svg',
    '/client/assets/players/alcaraz.png'
  ),
  (
    '3',
    '/client/assets/flags/es.svg',
    '/client/assets/players/nadal.png'
  ),
  (
    '4',
    '/client/assets/flags/gr.svg',
    '/client/assets/players/tsitsipas.png'
  ),
  (
    '5',
    '/client/assets/flags/no.svg',
    '/client/assets/players/ruud.png'
  ),
  (
    '6',
    '/client/assets/flags/ru.svg',
    '/client/assets/players/medvedev.png'
  ),
  (
    '7',
    '/client/assets/flags/ca.svg',
    '/client/assets/players/auger_aliassime.png'
  ),
  (
    '8',
    '/client/assets/flags/ru.svg',
    '/client/assets/players/rublev.png'
  ),
  (
    '9',
    '/client/assets/flags/us.svg',
    '/client/assets/players/fritz.png'
  ),
  (
    '10',
    '/client/assets/flags/dk.svg',
    '/client/assets/players/rune.png'
  );